services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tarefas
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=151430
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tarefas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 151430
    ports:
      - "5432:5432"
